### ISSUE TITLE
CSS paints the body red

### ISSUE THREAD

**Issue by ok200paul** [michalsnik/vue-content-placeholders#1]
Any reason for this? Trying to implement onto an existing project but it's converting the body to red..

**Comment by michalsnik** [comment]
Oh, I accidentally published code with some internal changes. Please try `0.2.1` :)

**Comment by michalsnik** [comment]
I installed it on a fresh project and seems to be working fine. Feel free to reopen if you'll find encounter any issues though :)

**Comment by ok200paul** [comment]
Cheers Michal!
