### ISSUE TITLE
content-placeholders component only renders the first sub-component

### ISSUE THREAD

**Issue by ok200paul** [michalsnik/vue-content-placeholders#2]
Maybe this is something I'm doing wrong (I'm not too flash at JS), but the `content-placeholders` component seems to be only displaying the first sub-component.  I've popped together a teeny app showing this here : https://github.com/ok200paul/placeholder-issue. 

What am I doing wrong? :)

**Comment by michalsnik** [comment]
Hey @ok200paul , I guess you didn't push everything to that repository. I tried to replicate your issue though with no luck. Below code seems to be working correctly:
```
<content-placeholders>
      <content-placeholders-heading :img="true" />
      <content-placeholders-text :lines="8" />
</content-placeholders>
```

**Comment by ok200paul** [comment]
How do you mean - have a look at the issue repo above - download the zip and open index.html in chrome (it's a vanilla install of the vue-content-placeholders component), only the first sub-component displays. When you say "Below code seems to be working correctly", could you provide a sample app?

**Comment by michalsnik** [comment]
Ah, I was expecting component to be in App.js

The problem in your case is that you use self-closed tags in `.html` file, and those only work when you write components in `.vue` files (vue-loader will parse them and convert to proper HTML tags)

Write:
```
<content-placeholders :rounded="true">
        <content-placeholders-img></content-placeholders-img>
        <content-placeholders-heading :img="true"></content-placeholders-heading>
        <content-placeholders-text></content-placeholders-text>
    </content-placeholders>
```
instead and you should see output correctly

**Comment by ok200paul** [comment]
Ahh - yes yes yes I get you okay - thanks for clarifying this. Thanks Michal, it's working now! I knew I was doing something incorrectly. Great component.
