### ISSUE TITLE
React placeholders

### ISSUE THREAD

**Issue by Geczy** [michalsnik/vue-content-placeholders#5]
Are you thinking about forking to react?

**Comment by danilowoz** [comment]
Congratulations @michalsnik on your great project! 
@Geczy I've worked on a similar project on React if you would like to meet [click here](https://github.com/danilowoz/react-content-loader)

**Comment by Geczy** [comment]
Just what I was looking for, thanks !

**Comment by michalsnik** [comment]
Thanks @danilowoz! I've seen yours too :D We had slightly different approaches, but both works cool :) I did it for Ember and now Vue. I was thinking about creating something with exactly the same API for React, but I probably won't find time to port it to React anytime soon. I'm glad @danilowoz already has a working solution :)
